oxygen_salle_de_sport_homepage:
    path:     /hello
    defaults: { _controller: OxygenSalleDeSportBundle:Default:index }
    
oxygen_salle_de_sport_profile_homepage:
    path:     /hi
    defaults: { _controller: OxygenSalleDeSportBundle:Default:afterLoginSuccess }
    
oxygen_salle_de_sport_profile_add_new_trainer:
    path:     /newTrainer
    defaults: { _controller: OxygenSalleDeSportBundle:Default:addNewTrainer }
   # methods:  [POST]

